version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      DB_HOST: db
      POSTGRES_DB: bid
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - /Users/shm/data/pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
